-- Create properties table with comprehensive property details and spatial indexes
CREATE TABLE IF NOT EXISTS properties (
    id INT PRIMARY KEY AUTO_INCREMENT,
    user_id INT NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    property_type ENUM('apartment', 'house', 'commercial', 'land') NOT NULL,
    listing_type ENUM('sale', 'rent') NOT NULL,
    status ENUM('new', 'resale', 'under_construction') NOT NULL,
    price DECIMAL(15,2) NOT NULL,
    area_sqft INT,
    bedrooms INT,
    bathrooms INT,
    address TEXT NOT NULL,
    city VARCHAR(100) NOT NULL,
    state VARCHAR(100) NOT NULL,
    postal_code VARCHAR(20),
    latitude DECIMAL(10, 8),
    longitude DECIMAL(11, 8),
    amenities JSON,
    is_featured BOOLEAN DEFAULT FALSE,
    is_active BOOLEAN DEFAULT TRUE,
    views_count INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    INDEX idx_user_id (user_id),
    INDEX idx_property_type (property_type),
    INDEX idx_listing_type (listing_type),
    INDEX idx_city (city),
    INDEX idx_state (state),
    INDEX idx_price (price),
    INDEX idx_area_sqft (area_sqft),
    INDEX idx_bedrooms (bedrooms),
    INDEX idx_bathrooms (bathrooms),
    INDEX idx_is_featured (is_featured),
    INDEX idx_is_active (is_active),
    INDEX idx_created_at (created_at),
    INDEX idx_location (latitude, longitude),
    FULLTEXT idx_title_description (title, description)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;