-- Create projects table
CREATE TABLE projects (
  id INT AUTO_INCREMENT PRIMARY KEY,
  builder_id INT NOT NULL,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  location VARCHAR(255) NOT NULL,
  address TEXT NOT NULL,
  city VARCHAR(100) NOT NULL,
  state VARCHAR(100) NOT NULL,
  pincode VARCHAR(10) NOT NULL,
  project_type ENUM('residential', 'commercial', 'mixed_use', 'villa', 'apartment', 'office', 'retail') NOT NULL,
  status ENUM('planning', 'pre_launch', 'under_construction', 'ready_to_move', 'completed', 'on_hold') NOT NULL DEFAULT 'planning',
  total_units INT NOT NULL DEFAULT 0,
  available_units INT NOT NULL DEFAULT 0,
  sold_units INT NOT NULL DEFAULT 0,
  blocked_units INT NOT NULL DEFAULT 0,
  start_date TIMESTAMP NULL,
  expected_completion TIMESTAMP NULL,
  actual_completion TIMESTAMP NULL,
  rera_number VARCHAR(100),
  approval_status VARCHAR(50) NOT NULL DEFAULT 'pending',
  amenities JSON,
  specifications JSON,
  pricing JSON,
  floor_plans JSON,
  brochure_url VARCHAR(500),
  video_url VARCHAR(500),
  virtual_tour_url VARCHAR(500),
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  featured BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_builder_id (builder_id),
  INDEX idx_status (status),
  INDEX idx_project_type (project_type),
  INDEX idx_city_state (city, state),
  INDEX idx_is_active (is_active),
  FOREIGN KEY (builder_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
