-- Create project_units table
CREATE TABLE project_units (
  id INT AUTO_INCREMENT PRIMARY KEY,
  project_id INT NOT NULL,
  unit_number VARCHAR(50) NOT NULL,
  unit_type VARCHAR(20) NOT NULL,
  floor_number INT NOT NULL,
  tower VARCHAR(10),
  area_sqft DECIMAL(10, 2) NOT NULL,
  area_sqm DECIMAL(10, 2) NOT NULL,
  price DECIMAL(15, 2) NOT NULL,
  price_per_sqft DECIMAL(10, 2) NOT NULL,
  maintenance_charge DECIMAL(10, 2),
  parking_spaces INT NOT NULL DEFAULT 0,
  balconies INT NOT NULL DEFAULT 0,
  bathrooms INT NOT NULL,
  bedrooms INT NOT NULL,
  status ENUM('available', 'sold', 'blocked', 'reserved') NOT NULL DEFAULT 'available',
  floor_plan_image VARCHAR(500),
  specifications JSON,
  amenities JSON,
  is_corner_unit BOOLEAN NOT NULL DEFAULT FALSE,
  has_terrace BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_project_id (project_id),
  INDEX idx_status (status),
  INDEX idx_unit_type (unit_type),
  UNIQUE KEY unique_project_unit (project_id, unit_number),
  FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
