import { User, UserRole } from '../../models/User';
import { Property, PropertyType, ListingType, PropertyStatus } from '../../models/Property';
import { PropertyImage } from '../../models/PropertyImage';

export async function seedIndividualProperties(users: User[]) {
  const owners = users.filter(u => u.role === UserRole.OWNER);
  const agents = users.filter(u => u.role === UserRole.AGENT);

  const properties = [
    // APARTMENTS (6 properties)
    {
      user_id: owners[0].id,
      title: 'Luxury 4BHK Penthouse in Bandra West',
      description: 'Ultra-luxury penthouse with 360-degree city and sea views, private terrace, premium Italian marble flooring, and world-class amenities.',
      property_type: PropertyType.APARTMENT,
      listing_type: ListingType.SALE,
      status: PropertyStatus.ACTIVE,
      price: 55000000,
      area_sqft: 3500,
      bedrooms: 4,
      bathrooms: 5,
      address: 'Palais Royale, Worli Sea Face',
      city: 'Mumbai',
      state: 'Maharashtra',
      postal_code: '400025',
      amenities: {
        parking: true,
        gym: true,
        swimming_pool: true,
        security: true,
        elevator: true,
        power_backup: true,
        air_conditioning: true,
        club_house: true
      },
      is_featured: true,
      is_active: true,
    },
    {
      user_id: agents[0].id,
      title: '2BHK Ready-to-Move Apartment in Andheri',
      description: 'Spacious 2BHK apartment with modern amenities, near metro station and shopping complexes. Perfect for young professionals.',
      property_type: PropertyType.APARTMENT,
      listing_type: ListingType.RENT,
      status: PropertyStatus.ACTIVE,
      price: 45000,
      area_sqft: 1200,
      bedrooms: 2,
      bathrooms: 2,
      address: 'Lokhandwala Complex, Andheri West',
      city: 'Mumbai',
      state: 'Maharashtra',
      postal_code: '400053',
      amenities: {
        parking: true,
        security: true,
        elevator: true,
        gym: true
      },
      is_featured: false,
      is_active: true,
    },
    {
      user_id: owners[1].id,
      title: '3BHK Luxury Apartment in Koramangala',
      description: 'Premium 3BHK apartment in prime Koramangala location with modern amenities and excellent connectivity.',
      property_type: PropertyType.APARTMENT,
      listing_type: ListingType.SALE,
      status: PropertyStatus.ACTIVE,
      price: 18500000,
      area_sqft: 1800,
      bedrooms: 3,
      bathrooms: 3,
      address: 'Koramangala 5th Block',
      city: 'Bangalore',
      state: 'Karnataka',
      postal_code: '560095',
      amenities: {
        parking: true,
        security: true,
        elevator: true,
        gym: true,
        swimming_pool: true
      },
      is_featured: true,
      is_active: true,
    },
    {
      user_id: agents[1].id,
      title: '1BHK Compact Apartment in Pune',
      description: 'Affordable 1BHK apartment perfect for bachelors or small families. Well-connected to IT parks.',
      property_type: PropertyType.APARTMENT,
      listing_type: ListingType.RENT,
      status: PropertyStatus.ACTIVE,
      price: 18000,
      area_sqft: 650,
      bedrooms: 1,
      bathrooms: 1,
      address: 'Hinjewadi Phase 1',
      city: 'Pune',
      state: 'Maharashtra',
      postal_code: '411057',
      amenities: {
        parking: true,
        security: true,
        elevator: true,
        power_backup: true
      },
      is_featured: false,
      is_active: true,
    },
    {
      user_id: owners[2].id,
      title: '3BHK Apartment with Balcony in Hyderabad',
      description: 'Spacious 3BHK with large balcony, modular kitchen, and premium fittings in gated community.',
      property_type: PropertyType.APARTMENT,
      listing_type: ListingType.SALE,
      status: PropertyStatus.NEW,
      price: 9500000,
      area_sqft: 1650,
      bedrooms: 3,
      bathrooms: 2,
      address: 'Gachibowli, Financial District',
      city: 'Hyderabad',
      state: 'Telangana',
      postal_code: '500032',
      amenities: {
        parking: true,
        security: true,
        elevator: true,
        gym: true,
        club_house: true,
        balcony: true
      },
      is_featured: true,
      is_active: true,
    },
    {
      user_id: agents[2].id,
      title: '2BHK Furnished Apartment in Delhi',
      description: 'Fully furnished 2BHK apartment with modern interiors, ready to move in. Close to metro station.',
      property_type: PropertyType.APARTMENT,
      listing_type: ListingType.RENT,
      status: PropertyStatus.ACTIVE,
      price: 35000,
      area_sqft: 1100,
      bedrooms: 2,
      bathrooms: 2,
      address: 'Dwarka Sector 12',
      city: 'Delhi',
      state: 'Delhi',
      postal_code: '110075',
      amenities: {
        parking: true,
        security: true,
        elevator: true,
        furnished: true,
        air_conditioning: true
      },
      is_featured: false,
      is_active: true,
    },

    // HOUSES (5 properties)
    {
      user_id: owners[1].id,
      title: 'Independent 3BHK House with Garden',
      description: 'Spacious independent house with private garden, car parking, and peaceful neighborhood. Ideal for families.',
      property_type: PropertyType.HOUSE,
      listing_type: ListingType.SALE,
      status: PropertyStatus.ACTIVE,
      price: 12500000,
      area_sqft: 2400,
      bedrooms: 3,
      bathrooms: 3,
      address: 'Koramangala 6th Block',
      city: 'Bangalore',
      state: 'Karnataka',
      postal_code: '560095',
      amenities: {
        parking: true,
        garden: true,
        security: true
      },
      is_featured: true,
      is_active: true,
    },
    {
      user_id: agents[1].id,
      title: 'Duplex House for Rent in Gurgaon',
      description: '4BHK duplex house in gated community with clubhouse, swimming pool, and 24/7 security.',
      property_type: PropertyType.HOUSE,
      listing_type: ListingType.RENT,
      status: PropertyStatus.ACTIVE,
      price: 65000,
      area_sqft: 2800,
      bedrooms: 4,
      bathrooms: 4,
      address: 'DLF Phase 4, Sector 28',
      city: 'Gurgaon',
      state: 'Haryana',
      postal_code: '122002',
      amenities: {
        parking: true,
        security: true,
        swimming_pool: true,
        club_house: true,
        gym: true
      },
      is_featured: false,
      is_active: true,
    },
    {
      user_id: owners[3].id,
      title: '5BHK Independent House in Jaipur',
      description: 'Luxurious 5BHK independent house with traditional Rajasthani architecture and modern amenities.',
      property_type: PropertyType.HOUSE,
      listing_type: ListingType.SALE,
      status: PropertyStatus.RESALE,
      price: 22000000,
      area_sqft: 3200,
      bedrooms: 5,
      bathrooms: 5,
      address: 'C-Scheme, Ashok Nagar',
      city: 'Jaipur',
      state: 'Rajasthan',
      postal_code: '302001',
      amenities: {
        parking: true,
        garden: true,
        security: true,
        terrace: true
      },
      is_featured: true,
      is_active: true,
    },
    {
      user_id: agents[3].id,
      title: '2BHK Row House in Ahmedabad',
      description: 'Modern row house with private parking and small garden. Part of well-maintained society.',
      property_type: PropertyType.HOUSE,
      listing_type: ListingType.SALE,
      status: PropertyStatus.ACTIVE,
      price: 7500000,
      area_sqft: 1500,
      bedrooms: 2,
      bathrooms: 2,
      address: 'Bopal, SG Highway',
      city: 'Ahmedabad',
      state: 'Gujarat',
      postal_code: '380058',
      amenities: {
        parking: true,
        garden: true,
        security: true,
        club_house: true
      },
      is_featured: false,
      is_active: true,
    },
    {
      user_id: owners[4].id,
      title: '4BHK Bungalow with Pool in Chandigarh',
      description: 'Elegant bungalow with private swimming pool, landscaped garden, and premium interiors.',
      property_type: PropertyType.HOUSE,
      listing_type: ListingType.SALE,
      status: PropertyStatus.ACTIVE,
      price: 35000000,
      area_sqft: 3800,
      bedrooms: 4,
      bathrooms: 5,
      address: 'Sector 9, Panchkula',
      city: 'Chandigarh',
      state: 'Chandigarh',
      postal_code: '134109',
      amenities: {
        parking: true,
        garden: true,
        swimming_pool: true,
        security: true,
        terrace: true
      },
      is_featured: true,
      is_active: true,
    },

    // VILLAS (3 properties)
    {
      user_id: owners[0].id,
      title: 'Luxury Beach Villa in ECR',
      description: 'Stunning 5BHK beach villa with direct beach access, infinity pool, and breathtaking ocean views.',
      property_type: PropertyType.VILLA,
      listing_type: ListingType.SALE,
      status: PropertyStatus.ACTIVE,
      price: 45000000,
      area_sqft: 4200,
      bedrooms: 5,
      bathrooms: 6,
      address: 'East Coast Road, Mahabalipuram',
      city: 'Chennai',
      state: 'Tamil Nadu',
      postal_code: '603104',
      amenities: {
        parking: true,
        garden: true,
        swimming_pool: true,
        security: true
      },
      is_featured: true,
      is_active: true,
    },
    {
      user_id: owners[2].id,
      title: 'Premium Villa in Goa',
      description: 'Portuguese-style villa with private pool, lush gardens, and modern amenities. Perfect vacation home.',
      property_type: PropertyType.VILLA,
      listing_type: ListingType.SALE,
      status: PropertyStatus.ACTIVE,
      price: 28000000,
      area_sqft: 3500,
      bedrooms: 4,
      bathrooms: 4,
      address: 'Candolim Beach Road',
      city: 'Goa',
      state: 'Goa',
      postal_code: '403515',
      amenities: {
        parking: true,
        garden: true,
        swimming_pool: true,
        security: true,
        furnished: true
      },
      is_featured: true,
      is_active: true,
    },
    {
      user_id: agents[2].id,
      title: 'Hill View Villa in Lonavala',
      description: 'Scenic villa with panoramic hill views, perfect for weekend getaways. Fully furnished.',
      property_type: PropertyType.VILLA,
      listing_type: ListingType.RENT,
      status: PropertyStatus.ACTIVE,
      price: 150000,
      area_sqft: 2800,
      bedrooms: 3,
      bathrooms: 3,
      address: 'Tungarli Lake Road',
      city: 'Lonavala',
      state: 'Maharashtra',
      postal_code: '410401',
      amenities: {
        parking: true,
        garden: true,
        security: true,
        furnished: true,
        terrace: true
      },
      is_featured: false,
      is_active: true,
    },

    // COMMERCIAL (4 properties)
    {
      user_id: owners[0].id,
      title: 'Premium Office Space in Business District',
      description: 'Grade A office space with modern amenities, central AC, and excellent connectivity to metro and airports.',
      property_type: PropertyType.COMMERCIAL,
      listing_type: ListingType.RENT,
      status: PropertyStatus.ACTIVE,
      price: 120000,
      area_sqft: 2500,
      bedrooms: 0,
      bathrooms: 3,
      address: 'Cyber City, DLF Phase 2',
      city: 'Gurgaon',
      state: 'Haryana',
      postal_code: '122002',
      amenities: {
        parking: true,
        elevator: true,
        security: true,
        power_backup: true,
        air_conditioning: true
      },
      is_featured: true,
      is_active: true,
    },
    {
      user_id: agents[0].id,
      title: 'Retail Showroom in Shopping Mall',
      description: 'Prime retail space in busy shopping mall with high footfall and excellent visibility.',
      property_type: PropertyType.COMMERCIAL,
      listing_type: ListingType.RENT,
      status: PropertyStatus.ACTIVE,
      price: 80000,
      area_sqft: 1200,
      bedrooms: 0,
      bathrooms: 2,
      address: 'Phoenix MarketCity, Whitefield',
      city: 'Bangalore',
      state: 'Karnataka',
      postal_code: '560066',
      amenities: {
        parking: true,
        security: true,
        air_conditioning: true
      },
      is_featured: false,
      is_active: true,
    },
    {
      user_id: owners[3].id,
      title: 'Commercial Building for Sale in Mumbai',
      description: 'Entire commercial building with 8 floors, suitable for corporate offices or co-working spaces.',
      property_type: PropertyType.COMMERCIAL,
      listing_type: ListingType.SALE,
      status: PropertyStatus.ACTIVE,
      price: 250000000,
      area_sqft: 25000,
      bedrooms: 0,
      bathrooms: 16,
      address: 'Andheri East, MIDC',
      city: 'Mumbai',
      state: 'Maharashtra',
      postal_code: '400093',
      amenities: {
        parking: true,
        elevator: true,
        security: true,
        power_backup: true,
        air_conditioning: true
      },
      is_featured: true,
      is_active: true,
    },
    {
      user_id: agents[3].id,
      title: 'Restaurant Space on Main Road',
      description: 'Prime restaurant space with kitchen setup, on busy main road with high visibility.',
      property_type: PropertyType.COMMERCIAL,
      listing_type: ListingType.RENT,
      status: PropertyStatus.ACTIVE,
      price: 95000,
      area_sqft: 1800,
      bedrooms: 0,
      bathrooms: 3,
      address: 'MG Road, Koramangala',
      city: 'Bangalore',
      state: 'Karnataka',
      postal_code: '560034',
      amenities: {
        parking: true,
        security: true,
        water_supply: true,
        power_backup: true
      },
      is_featured: false,
      is_active: true,
    },

    // PLOTS (3 properties)
    {
      user_id: owners[1].id,
      title: 'Premium Residential Plot in New Town',
      description: 'Well-located residential plot in approved layout with all utilities. Perfect for building your dream home.',
      property_type: PropertyType.PLOT,
      listing_type: ListingType.SALE,
      status: PropertyStatus.ACTIVE,
      price: 8500000,
      area_sqft: 2400,
      bedrooms: 0,
      bathrooms: 0,
      address: 'New Town, Action Area 1',
      city: 'Kolkata',
      state: 'West Bengal',
      postal_code: '700156',
      amenities: {
        water_supply: true,
        power_backup: true
      },
      is_featured: false,
      is_active: true,
    },
    {
      user_id: agents[1].id,
      title: 'Commercial Plot on Main Road',
      description: 'Prime commercial plot on busy main road with high visibility and excellent footfall potential.',
      property_type: PropertyType.PLOT,
      listing_type: ListingType.SALE,
      status: PropertyStatus.ACTIVE,
      price: 15000000,
      area_sqft: 1800,
      bedrooms: 0,
      bathrooms: 0,
      address: 'Ring Road, Surat',
      city: 'Surat',
      state: 'Gujarat',
      postal_code: '395007',
      amenities: {
        water_supply: true,
        power_backup: true
      },
      is_featured: true,
      is_active: true,
    },
    {
      user_id: owners[4].id,
      title: 'Agricultural Land near Highway',
      description: 'Fertile agricultural land with water source, suitable for farming or future development.',
      property_type: PropertyType.PLOT,
      listing_type: ListingType.SALE,
      status: PropertyStatus.ACTIVE,
      price: 12000000,
      area_sqft: 43560,
      bedrooms: 0,
      bathrooms: 0,
      address: 'NH-48, Vadodara',
      city: 'Vadodara',
      state: 'Gujarat',
      postal_code: '391240',
      amenities: {
        water_supply: true
      },
      is_featured: false,
      is_active: true,
    },

    // LAND (2 properties)
    {
      user_id: owners[2].id,
      title: 'Industrial Land for Development',
      description: 'Large industrial land parcel with all approvals, suitable for warehouse or manufacturing unit.',
      property_type: PropertyType.LAND,
      listing_type: ListingType.SALE,
      status: PropertyStatus.ACTIVE,
      price: 45000000,
      area_sqft: 87120,
      bedrooms: 0,
      bathrooms: 0,
      address: 'Chakan Industrial Area',
      city: 'Pune',
      state: 'Maharashtra',
      postal_code: '410501',
      amenities: {
        water_supply: true,
        power_backup: true
      },
      is_featured: true,
      is_active: true,
    },
    {
      user_id: agents[2].id,
      title: 'Residential Development Land',
      description: 'Prime land parcel approved for residential development, near upcoming metro station.',
      property_type: PropertyType.LAND,
      listing_type: ListingType.SALE,
      status: PropertyStatus.UNDER_CONSTRUCTION,
      price: 75000000,
      area_sqft: 130680,
      bedrooms: 0,
      bathrooms: 0,
      address: 'Sector 150, Noida',
      city: 'Noida',
      state: 'Uttar Pradesh',
      postal_code: '201310',
      amenities: {
        water_supply: true,
        power_backup: true
      },
      is_featured: true,
      is_active: true,
    },
  ];

  let createdCount = 0;
  for (const propertyData of properties) {
    try {
      const property = await Property.create(propertyData);
      console.log(`  🏠 Created property: ${property.title} in ${property.city}`);
      await addPropertyImages(property.id, property.property_type);
      createdCount++;
    } catch (error) {
      console.error(`❌ Error creating property: ${propertyData.title}`, error);
    }
  }

  console.log(`✅ Created ${createdCount} individual properties`);
}


async function addPropertyImages(propertyId: number, propertyType: PropertyType) {
  const imageMap: Record<PropertyType, string[]> = {
    [PropertyType.LAND]: [
      'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800',
      'https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=800',
    ],
    [PropertyType.APARTMENT]: [
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800',
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800',
    ],
    [PropertyType.HOUSE]: [
      'https://images.unsplash.com/photo-1600566753151-384129cf4e3e?w=800',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
      'https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=800',
    ],
    [PropertyType.VILLA]: [
      'https://images.unsplash.com/photo-1600607687644-aac4c3eac7f4?w=800',
      'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800',
      'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800',
    ],
    [PropertyType.COMMERCIAL]: [
      'https://images.unsplash.com/photo-1521791136064-7986c2920216?w=800',
      'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=800',
      'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800',
    ],
    [PropertyType.PLOT]: [
      'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800',
      'https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=800',
    ],
  };

  const images = imageMap[propertyType] || imageMap[PropertyType.APARTMENT];
  
  for (let i = 0; i < images.length; i++) {
    await PropertyImage.create({
      property_id: propertyId,
      image_url: images[i],
      alt_text: `Property Image ${i + 1}`,
      is_primary: i === 0,
      display_order: i + 1,
    });
  }
}
